/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/cb-InputBox.module';
export const cbInputBoxNgFactory:i0.NgModuleFactory<i1.cbInputBox> = i0.ɵcmf(i1.cbInputBox,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i1.cbInputBox,i1.cbInputBox,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya3NwYWNlL0hvdXNpbmcvVG9vbHMvY2JfaW9uaWNfaW5wdXQvc3JjL2NiLUlucHV0Qm94Lm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi93b3Jrc3BhY2UvSG91c2luZy9Ub29scy9jYl9pb25pY19pbnB1dC9zcmMvY2ItSW5wdXRCb3gubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7In0=
