/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/components/cb-InputBoxComponent';
const styles_cbInputBoxComponent:any[] = ([] as any[]);
export const RenderType_cbInputBoxComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_cbInputBoxComponent,data:{}});
export function View_cbInputBoxComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),6,'div',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted(-1,(null as any),['\n              '])),(_l()(),i0.ɵeld(2,0,(null as any),
      (null as any),1,'span',[['class','label label-md label-md-dark stacked']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted(3,
      (null as any),['',''])),(_l()(),i0.ɵted(-1,(null as any),['\n              '])),
      (_l()(),i0.ɵeld(5,0,(null as any),(null as any),0,'input',[['class','input input-md'],
          ['type','text']],[[8,'placeholder',0]],(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n            ']))],(null as any),
      (_ck,_v) => {
        var _co:i1.cbInputBoxComponent = _v.component;
        const currVal_0:any = _co.labelText;
        _ck(_v,3,0,currVal_0);
        const currVal_1:any = i0.ɵinlineInterpolate(1,'',_co.placeholderText,'');
        _ck(_v,5,0,currVal_1);
      });
}
export function View_cbInputBoxComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'cb-InputBoxComponent',
      ([] as any[]),(null as any),(null as any),(null as any),View_cbInputBoxComponent_0,
      RenderType_cbInputBoxComponent)),i0.ɵdid(1,49152,(null as any),0,i1.cbInputBoxComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const cbInputBoxComponentNgFactory:i0.ComponentFactory<i1.cbInputBoxComponent> = i0.ɵccf('cb-InputBoxComponent',
    i1.cbInputBoxComponent,View_cbInputBoxComponent_Host_0,{labelText:'labelText',
        placeholderText:'placeholderText'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya3NwYWNlL0hvdXNpbmcvVG9vbHMvY2JfaW9uaWNfaW5wdXQvc3JjL2NvbXBvbmVudHMvY2ItSW5wdXRCb3hDb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovd29ya3NwYWNlL0hvdXNpbmcvVG9vbHMvY2JfaW9uaWNfaW5wdXQvc3JjL2NvbXBvbmVudHMvY2ItSW5wdXRCb3hDb21wb25lbnQudHMiLCJuZzovLy9DOi93b3Jrc3BhY2UvSG91c2luZy9Ub29scy9jYl9pb25pY19pbnB1dC9zcmMvY29tcG9uZW50cy9jYi1JbnB1dEJveENvbXBvbmVudC50cy5jYklucHV0Qm94Q29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi93b3Jrc3BhY2UvSG91c2luZy9Ub29scy9jYl9pb25pY19pbnB1dC9zcmMvY29tcG9uZW50cy9jYi1JbnB1dEJveENvbXBvbmVudC50cy5jYklucHV0Qm94Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdj5cbiAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJsYWJlbCBsYWJlbC1tZCBsYWJlbC1tZC1kYXJrIHN0YWNrZWRcIj57e2xhYmVsVGV4dH19PC9zcGFuPlxuICAgICAgICAgICAgICA8aW5wdXQgdHlwZT1cInRleHRcIiBjbGFzcz1cImlucHV0IGlucHV0LW1kXCIgcGxhY2Vob2xkZXI9XCJ7e3BsYWNlaG9sZGVyVGV4dH19XCIgLz5cbiAgICAgICAgICAgIDwvZGl2PiIsIjxjYi1JbnB1dEJveENvbXBvbmVudD48L2NiLUlucHV0Qm94Q29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUs7YUFBQSx5Q0FDUztNQUFBO01BQUEsMERBQW1EO01BQUEsd0JBQW9CO01BQ3ZFO1VBQUE7VUFBQSxnQkFBOEU7OztRQUQzQjtRQUFBO1FBQ1Q7UUFBMUMsV0FBMEMsU0FBMUM7Ozs7b0JDRmQ7TUFBQTtvQ0FBQSxVQUFBO01BQUE7Ozs7In0=
